-- Первичная настройка Асық Arena в новом проекте Supabase.
-- Запустить целиком в Supabase Dashboard → SQL Editor → New query.
-- Скрипт рассчитан на новый проект и допускает повторный запуск.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Игрок',
  university text not null default 'Другой ВУЗ',
  created_at timestamptz not null default now(),
  constraint username_len check (char_length(username) between 1 and 20)
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  university text not null,
  level_id text not null,
  score integer not null,
  stars integer not null,
  created_at timestamptz not null default now(),
  constraint score_range check (score between 0 and 40),
  constraint stars_range check (stars between 0 and 3)
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skin_id text not null,
  created_at timestamptz not null default now(),
  constraint uniq_purchase unique (user_id, skin_id)
);

-- Обновляет ограничения и на таблицах, которые были созданы раньше.
alter table public.profiles drop column if exists email;
alter table public.profiles drop constraint if exists username_len;
alter table public.profiles add constraint username_len
  check (char_length(username) between 1 and 20);

alter table public.results drop constraint if exists score_range;
alter table public.results add constraint score_range
  check (score between 0 and 40);
alter table public.results drop constraint if exists stars_range;
alter table public.results add constraint stars_range
  check (stars between 0 and 3);

alter table public.purchases drop constraint if exists uniq_purchase;
alter table public.purchases add constraint uniq_purchase
  unique (user_id, skin_id);

-- RLS включён на всех пользовательских таблицах.
alter table public.profiles enable row level security;
alter table public.results enable row level security;
alter table public.purchases enable row level security;

drop policy if exists "Read own profile" on public.profiles;
create policy "Read own profile" on public.profiles
  for select to authenticated using (auth.uid() = id);

drop policy if exists "Read own results" on public.results;
create policy "Read own results" on public.results
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Insert own results" on public.results;
drop policy if exists "Authenticated users can insert results" on public.results;
create policy "Insert own results" on public.results
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Read own purchases" on public.purchases;
create policy "Read own purchases" on public.purchases
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Insert own purchases" on public.purchases;
create policy "Insert own purchases" on public.purchases
  for insert to authenticated with check (auth.uid() = user_id);

-- Создаёт профиль из метаданных регистрации Auth.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, username, university)
  values (
    new.id,
    left(coalesce(nullif(btrim(new.raw_user_meta_data->>'username'), ''), 'Игрок'), 20),
    coalesce(nullif(btrim(new.raw_user_meta_data->>'university'), ''), 'Другой ВУЗ')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

-- В рейтинге учитывается лучший результат игрока на каждом уровне.
create or replace view public.uni_leaderboard as
select university, sum(best)::int as total,
       count(distinct user_id)::int as players
from (
  select user_id, university, level_id, max(score) as best
  from public.results
  group by user_id, university, level_id
) best_by_level
group by university
order by total desc;

create or replace view public.player_leaderboard as
select username, university, sum(best)::int as total
from (
  select user_id, username, university, level_id, max(score) as best
  from public.results
  group by user_id, username, university, level_id
) best_by_level
group by user_id, username, university
order by total desc
limit 20;

-- Клиент читает личные данные через RLS, а публичный рейтинг — только через views.
grant usage on schema public to anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert on public.results to authenticated;
grant select, insert on public.purchases to authenticated;
grant select on public.uni_leaderboard, public.player_leaderboard to anon, authenticated;
